my:
  nettyPort: 9999
  requestMapping: /user
  fileMapping: /file


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.handsomelee.xyz:3306/metatrace?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf8
    username: admin
    password: lyh990322
    dbcp2:
      connection-init-sqls: set names utf8mb4

server:
  port: 10101